### ISSUE TITLE
Can't Install from Community Hass.io Add-ons Store

### ISSUE THREAD

**Issue by emouawad** [hassio-addons/addon-mqtt#13] opened 2018-11-28 15:40 UTC
# Problem/Motivation

> Can't Install from Hassio Addon Store

## Expected behavior

> Install Success and start configuration

## Actual behavior

> Unable to Install - Error:
`18-11-28 15:35:15 INFO (SyncWorker_19) [hassio.docker.interface] Pull image hassioaddons/mqtt tag 0.2.2.
18-11-28 15:35:33 ERROR (SyncWorker_19) [hassio.docker.interface] Can't install hassioaddons/mqtt:0.2.2 -> 404 Client Error: Not Found ("no such image: hassioaddons/mqtt:0.2.2: No such image: hassioaddons/mqtt:0.2.2").`

## Steps to reproduce

> Any Install - I am on hassio docker image (homeassistant/qemuarm-64-homeassistant)
   Ubuntu 16.04.5 LTS

**Comment by ludeeus** [comment] 2018-11-28 15:54
404 usually means that there is no space left on the device

**Comment by emouawad** [comment] 2018-11-28 17:05
Hardly in this case - I just confirmed again i still have at least 3GB - and i can install other addons no problem

**Comment by ludeeus** [comment] 2018-11-28 21:19
Don't know what to tell you...
2 things can cause that error.

1. The tag does not exist https://hub.docker.com/r/hassioaddons/mqtt/tags/ (it does).
2. There is not enough space left on the device.

**Comment by emouawad** [comment] 2018-11-29 09:02
Maybe something with the docker installer - can't find the image corresponding to my device architecture? Mine is A64 same as pine64 - http://www.orangepi.org/OrangePiWin_WinPlus/

**Comment by ludeeus** [comment] 2018-11-29 09:50
That will be `aarch64` and it's there too ;)

**Comment by ludeeus** [comment] 2019-01-01 20:09
Closing this as the issue is not replicable.
Possible issues for 404 error from Docker Hub

- The tag does not exist https://hub.docker.com/r/hassioaddons/mqtt/tags/ (it does).
- There is not enough space left on the device.

**Closed by ludeeus** 2019-01-01 20:09 UTC
